### ISSUE TITLE
결제 생성 로직 변경

### ISSUE THREAD

**Issue by joo-chang** [for-men/ForTickets#111]
### TODO

- [x]  예매 확정 API 삭제 → 예매 확정에 있는 검증 로직 결제 생성으로 이동해야함
- [x]  confirm.html 요청 url 결제 생성으로 변경 해야함
- [x]  결제 요청 API 이름 변경 → 결제 완료

현재 flow - 예매 생성 → 예매 확정(결제 생성) → 결제 요청(결제 완료, 예매 확정) 
로직         - 예매 생성 → 결제 생성 → 결제 완료, 예매 확정
변경 flow - 예매 생성 → 결제 생성 → 결제 완료
