### ISSUE TITLE
서비스 내 Resilience 패턴 적용 

### ISSUE THREAD

**Issue by uzjaee** [for-men/ForTickets#52]
## 개요 ## 
서비스간 호출 시 실패 상황시 대비책과 실패상태를 관리할 수 있는 패턴을 적용합니다. 
Resilience 패턴에 해당하는 FallBack과 Circuit Breaker의 연계를 통해 서비스의 안정성을 강화합니다. 

## todo ## 

- [x] 서비스 내 feign client 사용 지점 파악 
- [x] Fallback 개념 공부
- [x] Circuit Breaker 개념 공부 
- [x] Fallback과 Circuit Breaker의 연계
- [ ] 서비스 내 테스트
